### ISSUE TITLE
Can you add me and @tooky as contributors please?

### ISSUE THREAD

**Issue by mattwynne** [fedux-org/event-bus#3]
Also please make us gem owners so we can do releases if necessary.

I think it's fine for this to remain with you as the owner - no need to move it under the cucumber org.

**Comment by dg-ratiodata** [comment]
Done. I also moved it to fedux-org. You've got full admin rights for that repository.

**Comment by dg-ratiodata** [comment]
Can you try to access this repo?

**Comment by mattwynne** [comment]
Looks good. Can we be gem owners too please? Use matt at mattwynne.net <http://mattwynne.net/> as my ruby gems email. I think tooky is steve at boxjump.com

**Comment by dg-ratiodata** [comment]
@mattwynne I added you as owner, @tooky's given mail address did not work. I tried steve at heavi dot es, which worked. @tooky I hope that's the correct one. I found it [here](https://rubygems.org/profiles/tooky).
